### ISSUE TITLE
请求作者主页所有作品失败，警告“接口未返回数据, 正在重新请求!”

### ISSUE THREAD

**Issue by windcolor** [imgyh/tiktok#16]
前几天还能用，但昨天开始，获取主页所有作品失败，只能在前两次请求时,能获取到作品的id，但后面就不行了
然后一直提示没返回数据，提示超过10秒后，最终显示失败

[  警告  ]:接口未返回数据, 正在重新请求!
[  警告  ]:接口未返回数据, 正在重新请求!
[  警告  ]:接口未返回数据, 正在重新请求!
[  警告  ]:接口未返回数据, 正在重新请求!
[  警告  ]:接口未返回数据, 正在重新请求!
[  警告  ]:接口未返回数据, 正在重新请求!
[  警告  ]:接口未返回数据, 正在重新请求!
Traceback (most recent call last):
  File "TikTok.py", line 193, in getUserInfo
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "TikTokCommand.py", line 101, in <module>
  File "TikTokCommand.py", line 61, in main
  File "TikTok.py", line 201, in getUserInfo
RuntimeError: 重复请求该接口10s, 仍然未获取到数据
[29584] Failed to execute script 'TikTokCommand' due to unhandled exception!

**Comment by zhangya4548** [comment]
今天也是获取不了内容了

**Comment by imgyh** [comment]
加个sid_guard参数就行了，马上更新配置文件版本的，用自己的cookie
